- name: Check if node is already in Swarm
  command: docker info
  register: docker_info
  changed_when: false

- name: Initialize Swarm (manager only)
  shell: docker swarm init --advertise-addr {{ ansible_host }}
  when:
    - inventory_hostname in groups['manager_node']
    - "'Swarm: inactive' in docker_info.stdout"

- name: Get join token (run only on manager)
  command: docker swarm join-token worker -q
  register: join_token
  when:
    - inventory_hostname == groups['manager_node'][0]
  delegate_to: "{{ groups['manager_node'][0] }}"
  run_once: true

- name: Set worker join token as fact for all nodes
  set_fact:
    worker_join_token: "{{ join_token.stdout }}"
  when: inventory_hostname in groups['worker_node']

- name: Check if worker is already part of Swarm
  command: docker info
  register: worker_info
  changed_when: false
  when: inventory_hostname in groups['worker_node']

- name: Join Swarm (only if inactive)
  shell: docker swarm join --token {{ worker_join_token }} {{ hostvars[groups['manager_node'][0]].ansible_host }}:2377
  when:
    - inventory_hostname in groups['worker_node']
    - "'Swarm: inactive' in worker_info.stdout"

